### ISSUE TITLE
Openmodelica compatibility

### ISSUE THREAD

**Issue by Hofsmo** [DLR-SR/AdvancedNoise#16]
Hi,
Your library looks very interesting, however, I have had no success running either of the versions on openmodelica. Do you know whehter or not it has been tested on openmodelica?

Best regards,
Sigurd

**Comment by akloeckner** [comment]
The basic functionality of noise modeling is available in the Modelica Standard Library 3.2.2 and has been developed so that it works with several Modelica tools including OpenModelica. 

If your OpenModelica installation does not yet support MSL 3.2.2, a working copy of this additional functionality is available through the [Modelica_Noise](https://github.com/DLR-SR/Noise) library. This copy should work with OpenModelica and it is included in the [Noise 0.9.1](https://github.com/DLR-SR/AdvancedNoise/archive/v0.9.1.zip) bundle.

If your OpenModelica installation supports MSL 3.2.2, you should have the Modelica_Noise features already in the Blocks.Noise package. The [Noise 1.0.0](https://github.com/DLR-SR/AdvancedNoise/archive/v1.0.0.zip) bundle (or the [AdvancedNoise](https://github.com/DLR-SR/AdvancedNoise) master branch) then contains additional functionality.

However, the additional functionality available in AdvancedNoise uses more advanced features of the Modelica language and this part has been developed and tested only with Dymola. At least some functionality should also work in OpenModelica, though. We would be very happy, if you could provide PullRequests for things that do not work in this tool!

**Comment by thorade** [comment]
The AdvancedNoise library is tested every night or so with the latest OpenModelica code:
https://libraries.openmodelica.org/branches/master/AdvancedNoise/AdvancedNoise.html

or with released versions:
https://libraries.openmodelica.org/branches/v1.12/AdvancedNoise/AdvancedNoise.html
https://libraries.openmodelica.org/branches/v1.11/AdvancedNoise/AdvancedNoise.html
https://libraries.openmodelica.org/branches/v1.9/AdvancedNoise/AdvancedNoise.html

All models with an experiment annotation are included in the tests.
