### ISSUE TITLE
Public non-inputs or outputs in function

### ISSUE THREAD

**Issue by adrpo** [DLR-SR/AdvancedNoise#21]
[AdvancedNoise 1.0.0/Generators/QuickXorshift64star/package.mo:13:5-13:62:writable] Warning: Invalid public variable p, function variables that are not input/output must be protected.

See more on the discussion here:
https://trac.openmodelica.org/OpenModelica/ticket/5061

I guess you should move the parameter to the protected section.

**Comment by tobolar** [comment]
Quickly checking the example `AdvancedNoise.Examples.SignalBasedInterpolation`, I have realized the number of random state iterations (done in `AdvancedNoise.Generators.QuickXorshift64star.initialState`) could influence CPU time significantly. 
Therefore, it would be better to let `p` be a function input instead of protected parameter.

There is another discrepancy as well. The `QuickXorshift64star.initialState` documentation states 
> To be on the safe side, actually 10 random numbers are generated ...

but actually, p=1.

So we could take some tradeoff:
`  input Integer p = 5 "The number of iterations to use";`
and adapt the documentation accordingly
`To be on the safe side, actually 5 random numbers are generated and the returned state is the one from the last iteration. The number of iterations could be modified by input <code>p</code>.`
