### ISSUE TITLE
Ambiguous message of an assert in FixedGridStepResponse.interpolate 

### ISSUE THREAD

**Issue by tobolar** [DLR-SR/AdvancedNoise#6]
In AdvancedNoise.Interpolators.FixedGridStepResponse.interpolate there is an assert returning "You need to use the suggestedSamplePeriod with the FixedGridStepResponse interpolator!" if violated. I'm not sure if this message is helpful (especially if using other interpolation which extends this one, such as AdvancedNoise.Examples.RailIrregularities.RailZeroPhaseInterpolator) since just applying a samplePeriod close to the suggestedSamplePeriod will solve the problem.

So may be a message like "Set samplePeriod close to suggestedSamplePeriod" could be more suitable.

Or may be there exists even a better solution to spare the user to change the samplePeriod which HAS TO be close to the suggestedSamplePeriod.

**Comment by akloeckner** [comment]
We have ```AdvancedNoise.Sources.ColoredSignalBasedNoise```, which actually uses the ```suggestedSamplePeriod```. We might make this parameter final maybe, so it cannot be changed to a nonsense value...

If the above model is used, everything is set up correctly. But the interpolator can also be used together with the more general ```AdvancedNoise.Sources.TimeBasedNoise```. This is what the warning is for: The sample period must then actually be set not close to, but exactly to the suggested sample period, because the fixed grid convolution assumes this. However, I could not think of a way to properly compare the Real values without using a tolerance.

If you have suggestions, I'll be happy to hear them!

**Comment by akloeckner** [comment]
I close this issue as the current solution is the best I can think of. Please re-open, if you have better ideas. @tobolar
